apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-configmap
data:
  # SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://config-server-service:8071/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8070/eureka/
  EUREKA_APPLICATION_NAME: eureka-server
  ACCOUNTS_APPLICATION_NAME: bank-accounts
